//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBilling.ServicioCertificadoV4 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoCertificadoResponse", Namespace="http://schemas.datacontract.org/2004/07/ServiceSoap.UBL2._0.Response")]
    [System.SerializableAttribute()]
    public partial class EstadoCertificadoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eBilling.ServicioCertificadoV4.Certificado certificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eBilling.ServicioCertificadoV4.Certificado certificado {
            get {
                return this.certificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.certificadoField, value) != true)) {
                    this.certificadoField = value;
                    this.RaisePropertyChanged("certificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadoField, value) != true)) {
                    this.resultadoField = value;
                    this.RaisePropertyChanged("resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Certificado", Namespace="http://schemas.datacontract.org/2004/07/ServiceSoap.Models.Response")]
    [System.SerializableAttribute()]
    public partial class Certificado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identificationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string active {
            get {
                return this.activeField;
            }
            set {
                if ((object.ReferenceEquals(this.activeField, value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dateFrom {
            get {
                return this.dateFromField;
            }
            set {
                if ((object.ReferenceEquals(this.dateFromField, value) != true)) {
                    this.dateFromField = value;
                    this.RaisePropertyChanged("dateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dateTo {
            get {
                return this.dateToField;
            }
            set {
                if ((object.ReferenceEquals(this.dateToField, value) != true)) {
                    this.dateToField = value;
                    this.RaisePropertyChanged("dateTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identification {
            get {
                return this.identificationField;
            }
            set {
                if ((object.ReferenceEquals(this.identificationField, value) != true)) {
                    this.identificationField = value;
                    this.RaisePropertyChanged("identification");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCertificadoV4.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EstadoCertificado", ReplyAction="http://tempuri.org/IService/EstadoCertificadoResponse")]
        eBilling.ServicioCertificadoV4.EstadoCertificadoResponse EstadoCertificado(string tokenEmpresa, string tokenPasswords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EstadoCertificado", ReplyAction="http://tempuri.org/IService/EstadoCertificadoResponse")]
        System.Threading.Tasks.Task<eBilling.ServicioCertificadoV4.EstadoCertificadoResponse> EstadoCertificadoAsync(string tokenEmpresa, string tokenPasswords);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : eBilling.ServicioCertificadoV4.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<eBilling.ServicioCertificadoV4.IService>, eBilling.ServicioCertificadoV4.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public eBilling.ServicioCertificadoV4.EstadoCertificadoResponse EstadoCertificado(string tokenEmpresa, string tokenPasswords) {
            return base.Channel.EstadoCertificado(tokenEmpresa, tokenPasswords);
        }
        
        public System.Threading.Tasks.Task<eBilling.ServicioCertificadoV4.EstadoCertificadoResponse> EstadoCertificadoAsync(string tokenEmpresa, string tokenPasswords) {
            return base.Channel.EstadoCertificadoAsync(tokenEmpresa, tokenPasswords);
        }
    }
}
